### ISSUE TITLE
enum34 package is causing an error "Dell EMC OMSDK library" required even though OMSDK package is installed

### ISSUE THREAD

**Issue by wilfredm91** [vaideesg/omsdk#26] opened 2017-09-14 11:40 UTC

**Comment by vaideesg** [comment] 2017-09-15 12:14
Duplicate of #11. Fixed as part of that checkin

**Comment by vaideesg** [comment] 2017-09-15 12:14
Duplicate of #11. Fixed as part of that checkin

**Comment by vaideesg** [comment] 2017-09-15 12:14
Duplicate of #11. Fixed as part of that checkin

**Closed by vaideesg** 2017-09-15 12:14 UTC

**Comment by vaideesg** [comment] 2017-09-15 12:16
Duplicate of #11. Fixed as part of that checkin

**Comment by vaideesg** [comment] 2017-09-15 12:16
Duplicate of #11. Fixed as part of that checkin
